### ISSUE TITLE
Actividad 2-Infografía/Daisy Gonzalez Lita

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-2-infografia-Daisy-GonzalezLita12#1]
Actividad 2-Infografía
Alumna: Daisy González Lita 
Grupo: 1BS
[Infografia_Daisy_González_Lita.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-Daisy-GonzalezLita12/files/9465227/Infografia_Daisy_Gonzalez_Lita.pdf)

**Comment by AmeliReyesHernandez** [comment]
18.8 de 20

**Comment by AmeliReyesHernandez** [comment]
18.4

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
